seo:
  site_name: Villa
  title: Villa
  description:
  keywords:
  social_image:
  author:
  favicon_image:
social:
  instagram_username:
  facebook_url:
  twitter_username:
design:
  beige-color: '#ECE4D2'
  sand-color: '#CCBFA4'
  green-color: '#889669'
  kaki-color: '#373E29'
  bg-dark: '#373E29'
  bg-light: '#CCBFA4'
  bg-sand: '#CCBFA4'
  body-text: '#4A4444'