seo:
  site_name: Villa
  title: Villa
  description:
  keywords:
  social_image:
  author:
  favicon_image:
social:
  instagram_username:
  facebook_url:
  twitter_username:
design:
  rose_color: '#D28D6E'
  sand_color: '#D48743'
  beige_color: '#E1D5BD'
  featured_color: '#883618'
  bg-light_color: '#E1D5BD'
  bg-sand_color: '#D48743'
  bg-rose_color: '#D28D6E'
  bg-dark_color: '#883618'
  body-text_color: '#4A4444'