seo:
  site_name: Villa
  title: Villa
  description:
  keywords:
  social_image:
  author:
  favicon_image:
social:
  instagram_username:
  facebook_url:
  twitter_username:
design:
  beige-color_color: '#ECE4D2'
  sand-color_color: '#CCBFA4'
  green-color_color: '#889669'
  kaki-color_color: '#373E29'
  bg-dark_color: '#373E29'
  bg-light_color: '#CCBFA4'
  bg-sand_color: '#CCBFA4'
  body-text_color: '#4A4444'